# Generated by Django 4.1.7 on 2023-04-09 17:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_likes_news_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'қолданушы', 'verbose_name_plural': 'Қолданушылар'},
        ),
        migrations.AlterModelOptions(
            name='last_news_date',
            options={'ordering': ['id'], 'verbose_name': 'Соңғы тауар', 'verbose_name_plural': 'Соңғы тауар'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Өнім', 'verbose_name_plural': 'Өнімдер'},
        ),
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1000, max_digits=12, verbose_name='Бағасы'),
        ),
        migrations.AddField(
            model_name='news',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Өнім саны'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='электорондық пошта'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Тегі'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Әкесінің ааты'),
        ),
        migrations.AlterField(
            model_name='last_news_date',
            name='last_news_date',
            field=models.DateTimeField(verbose_name='Соңғы шыққаан жаңалықтар арналған кезең'),
        ),
        migrations.AlterField(
            model_name='last_news_date',
            name='trues',
            field=models.BooleanField(default=False, verbose_name='Осы кезең'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(db_index=True, default='0', max_length=150, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_text',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Өнім толық сипатамасы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='context',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Өнім қысқаша сипаттамасы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_add',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Өнім шыққаан күні'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, db_index=True, upload_to='', verbose_name='Сурет 1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Сурет 2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Сурет 3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайктар'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_news',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Көшбасшы өнімдер'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='қосымшаға шығару'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Өнім'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='value',
            field=models.CharField(choices=[('Like', True), ('Unlike', False)], default='Like', max_length=8, verbose_name='лайк көрсеткіші'),
        ),
    ]
