# Generated by Django 4.1.7 on 2023-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Жалпы сомасы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='addres',
            field=models.CharField(default='Астна, Бейінбет майлина 3/4 ,13 кв, 1 подьезд', max_length=250, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Тапсырыс қабылданды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ver_order',
            field=models.BooleanField(default=False, verbose_name='Тапсырыс орындалды'),
        ),
    ]
