# Generated by Django 4.1.7 on 2023-04-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_order_totalprice_alter_order_addres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
    ]
