# Generated by Django 4.1.7 on 2023-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_remove_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addres',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Астна, Бейінбет майлина 3/4 ,13 кв, 1 подьезд', max_length=250, verbose_name='Адрес'),
        ),
    ]
